name: collective.transmute linting

on:
  push:

env:
  PYTHON_VERSION: "3.12"

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Install the latest version of uv
          uses: astral-sh/setup-uv@v5
          with:
            python-version: ${{ env.PYTHON_VERSION }}

        - name: Check formatting
          if: ${{ success() || failure() }}
          id: ruff-format
          run: uvx ruff@latest format --diff

        - name: Check lint
          if: ${{ success() || failure() }}
          id: ruff-lint
          run: uvx ruff@latest check --diff

        - name: Check Package Metadata
          if: ${{ success() || failure() }}
          id: pyroma
          run: uvx pyroma@latest -d .

        - name: Check Python Versions
          if: ${{ success() || failure() }}
          id: py-versions
          run: uvx check-python-versions@latest .

        - name: Check typing
          if: ${{ success() || failure() }}
          id: typing
          run: |
            make install
            uv run mypy src

        - name: Report
          if: ${{ success() || failure() }}
          run: |
            echo '# Code Analysis' >> $GITHUB_STEP_SUMMARY
            echo '| Test | Status |' >> $GITHUB_STEP_SUMMARY
            echo '| --- | --- |' >> $GITHUB_STEP_SUMMARY
            echo '| Format | ${{ steps.ruff-format.conclusion == 'failure' && '❌' || ' ✅' }} |' >> $GITHUB_STEP_SUMMARY
            echo '| Lint | ${{ steps.ruff-lint.conclusion == 'failure' && '❌' || ' ✅' }} |' >> $GITHUB_STEP_SUMMARY
            echo '| Package Metadata | ${{ steps.pyroma.conclusion == 'failure' && '❌' || ' ✅' }} |' >> $GITHUB_STEP_SUMMARY
            echo '| Python Versions | ${{ steps.py-versions.conclusion == 'failure' && '❌' || ' ✅' }} |' >> $GITHUB_STEP_SUMMARY
            echo '| Typing | ${{ steps.typing.conclusion == 'failure' && '❌' || ' ✅' }} |' >> $GITHUB_STEP_SUMMARY
